Fixing hexapod API to properly return success flag
Interbotix/interbotix_ros_toolboxes pull request #13
Opened 2022-01-11 23:38 UTC by AVSurfer123

As stated, this PR fixes the two functions `modify_stance` and `move_leg` to properly return True when the function succeeds and False when it fails.

2022-01-12 16:52 UTC, LSinterbotix requested changes
1. Good changes in hexapod.py. I would just ask that you add a return description to the modify_stance and move_leg docstrings. Take a look at the other functions for examples.
2. As for the CATKIN_IGNORE deletions - please restore those. The structure of our repositories and our installation methods require that they exist.

Once those changes are made, I can merge this PR.

2022-01-13 20:48 UTC, AVSurfer123 commented
1. Finished
2. Sorry, I removed it for our fork but forgot to keep it in for the PR. I've reverted that commit
3. Done

2022-01-13 20:58 UTC, LSinterbotix approved these changes

2022-01-13 21:08 UTC, merged

2022-01-13 21:14 UTC, LSinterbotix commented
@AVSurfer123 Thanks for the contribution!