Feature: Moveit Interface Python Core
Interbotix/interbotix_ros_toolboxes pull request #53
Opened 2023-10-18 00:59 UTC by pinakjani

This feature includes the implementation of a new core **Moveit2 Python API**.

The Moveit2 Python API is wrapped around by **Interbotix Arm Wrapper** in the `move_arm.py`. 

To use this new Interbotix Arm Moveit Python API one needs to import the `move_arm` module from `interbotix_moveit_interface` package.

2023-10-18 01:17 UTC, pinakjani commented
Fixed known changes. Do we have lint check here?

Looking forward to many changes comments ;)

2023-10-25 17:14 UTC, LSinterbotix commented
If you want to pre-emptively run tests, you can build the tests:

```
colcon build --packages-select [packages] --cmake-args -DBUILD_TESTING=ON
```

and run the tests:

```
colcon test --packages-select [packages]
```

and check the logs

```
cat log/latest_test/[package]/stdout_stderr.log
```

2023-10-26 16:48 UTC, LSinterbotix commented
This PR should target the `xscobots` branch.

2023-11-16 22:12 UTC, LSinterbotix requested changes
We don't want to remove the existing `interbotix_moveit_interface`. Our typical organizational pattern for Python libraries/modules is to create an `interbotix_<something>_modules` package. I would suggest moving all of the moveit_arm and related files into their own package and restoring the state of the `interbotix_moveit_interface` package.

Things like launch files, configuration files, RViz configs, etc. live in whatever main package they're launched from. In this case, I guess they would be located in the interbotix_xscobot_moveit package. Is that an issue? Can we reuse the same configs there with the same functionality?

We also want to allow users to send service requests (torque, get registers, etc.). For this, we typically create an `InterbotixRobotXSCore`. However, this object creates a node. I'm assuming the `moveit.planning.MoveItPy` object does the same. Is there a way we can get around this? Can we refactor all the older code so a node is only created if we don't already have one/one isn't passed to the object? Can we also only have one MoveItPy instance per process? What do you think?

2023-11-16 22:12 UTC, LSinterbotix commented on interbotix_common_toolbox/interbotix_moveit_interface/interbotix_moveit_interface/move_arm.py
> +class InterbotixArmXSInterface:
Would name this and `InterbotixGripperXSInterface` differently so they don't conflict with the original classes. Maybe something like `InterbotixMoveItArmXSInterface`. Not sure about how verbose that is but

2023-11-16 22:12 UTC, LSinterbotix commented on interbotix_common_toolbox/interbotix_moveit_interface/interbotix_moveit_interface/move_arm.py
> +class InterbotixGripperXSInterface:
Would suggest making a moveit_gripper.py module and moving this there.

2023-11-16 22:12 UTC, LSinterbotix commented on interbotix_common_toolbox/interbotix_moveit_interface/interbotix_moveit_interface/move_arm.py
> +        # instantiate moveit_py instance and a planning component for the panda_arm
panda arm

2023-11-16 22:12 UTC, LSinterbotix commented on interbotix_common_toolbox/interbotix_moveit_interface/interbotix_moveit_interface/moveit_interface_core.py
> +    time.sleep(sleep_time)
should use `get_clock().sleep_for()` instead.

2024-04-11 17:20 UTC, closed without merging